from __future__ import annotations

import json
import re
from dataclasses import asdict

import requests

from config import Settings
from models import AIClassification, ChannelSnapshot


class OllamaClassifier:
    def __init__(self, settings: Settings) -> None:
        self.settings = settings
        self.base = settings.ollama_base_url.rstrip("/")

    def check(self) -> tuple[bool, str]:
        try:
            response = requests.get(f"{self.base}/api/tags", timeout=8)
            response.raise_for_status()
            names = {item.get("name", "") for item in response.json().get("models", [])}
            model = self.settings.ollama_model
            exists = model in names or any(name.split(":")[0] == model.split(":")[0] for name in names)
            if not exists:
                return False, f"Model {model!r} not found. Available: {', '.join(sorted(names)) or 'none'}"
            return True, "ok"
        except Exception as exc:
            return False, str(exc)

    def classify(self, snapshot: ChannelSnapshot) -> AIClassification:
        content = self._build_content(snapshot)
        system = (
            "You are a local-only Telegram channel safety classifier. "
            "Classify CHANNEL/SUPERGROUP content for account cleanup. "
            "Do not judge ordinary politics, news, memes, gaming, technology or normal advertising as spam merely because you dislike it. "
            "adult_score: explicit pornography, sexual services, nude/explicit sexual content, porn links. "
            "spam_score: scam, phishing, mass unsolicited promotion, fake giveaways, obvious deceptive schemes, repetitive promo spam. "
            "junk_score: low-value autogenerated/repetitive channel feed with little useful content. "
            "Return conservative probabilities from 0 to 1. If uncertain, use lower scores. "
            "Return ONLY valid JSON with keys adult_score, spam_score, junk_score, category, reason. "
            "category must be one of: adult, spam, junk, normal, uncertain. "
            "reason must be short, neutral, and must not quote explicit content."
        )
        payload = {
            "model": self.settings.ollama_model,
            "stream": False,
            "format": "json",
            "think": False,
            "messages": [
                {"role": "system", "content": system},
                {"role": "user", "content": content},
            ],
            "options": {
                "temperature": 0.05,
                "top_p": 0.8,
                "num_predict": 220,
            },
        }
        response = requests.post(
            f"{self.base}/api/chat",
            json=payload,
            timeout=self.settings.ollama_timeout,
        )
        response.raise_for_status()
        data = response.json()
        raw = data.get("message", {}).get("content", "").strip()
        parsed = self._parse_json(raw)
        return AIClassification(
            adult_score=self._score(parsed.get("adult_score")),
            spam_score=self._score(parsed.get("spam_score")),
            junk_score=self._score(parsed.get("junk_score")),
            category=str(parsed.get("category", "uncertain"))[:24],
            reason=str(parsed.get("reason", "No reason returned"))[:280],
        )

    def should_remove(self, result: AIClassification) -> bool:
        return (
            result.adult_score >= self.settings.adult_threshold
            or result.spam_score >= self.settings.spam_threshold
            or result.junk_score >= self.settings.junk_threshold
        )

    def _build_content(self, snapshot: ChannelSnapshot) -> str:
        messages = []
        consumed = 0
        for item in snapshot.recent_messages:
            clean = re.sub(r"\s+", " ", item).strip()
            if not clean:
                continue
            remaining = self.settings.max_text_chars - consumed
            if remaining <= 0:
                break
            messages.append(clean[: min(1200, remaining)])
            consumed += len(messages[-1])

        metadata = asdict(snapshot)
        metadata.pop("recent_messages", None)
        return (
            "Channel metadata:\n"
            + json.dumps(metadata, ensure_ascii=False, indent=2)
            + "\n\nRecent text messages/captions:\n"
            + "\n---\n".join(messages)
        )[: self.settings.max_text_chars]

    @staticmethod
    def _score(value: object) -> float:
        try:
            return min(1.0, max(0.0, float(value)))
        except (TypeError, ValueError):
            return 0.0

    @staticmethod
    def _parse_json(raw: str) -> dict:
        try:
            return json.loads(raw)
        except json.JSONDecodeError:
            match = re.search(r"\{.*\}", raw, re.DOTALL)
            if not match:
                raise ValueError(f"Ollama returned non-JSON output: {raw[:200]}")
            return json.loads(match.group(0))
